/**
 * Design System Configuration
 * Generated by UI Designer Agent
 *
 * Complete design tokens for the Workforce Transition Platform
 * Implements Material Design 3 principles with custom theming
 */

export const designSystem = {
  // ==================== Color Palette ====================
  colors: {
    primary: {
      50: '#E3F2FD',
      100: '#BBDEFB',
      200: '#90CAF9',
      300: '#64B5F6',
      400: '#42A5F5',
      500: '#2196F3',  // Main brand color
      600: '#1E88E5',
      700: '#1976D2',
      800: '#1565C0',
      900: '#0D47A1',
    },
    secondary: {
      50: '#F3E5F5',
      100: '#E1BEE7',
      200: '#CE93D8',
      300: '#BA68C8',
      400: '#AB47BC',
      500: '#9C27B0',  // Accent color
      600: '#8E24AA',
      700: '#7B1FA2',
      800: '#6A1B9A',
      900: '#4A148C',
    },
    success: {
      50: '#E8F5E9',
      100: '#C8E6C9',
      500: '#4CAF50',
      700: '#388E3C',
      900: '#1B5E20',
    },
    warning: {
      50: '#FFF3E0',
      100: '#FFE0B2',
      500: '#FF9800',
      700: '#F57C00',
      900: '#E65100',
    },
    error: {
      50: '#FFEBEE',
      100: '#FFCDD2',
      500: '#F44336',
      700: '#D32F2F',
      900: '#B71C1C',
    },
    info: {
      50: '#E1F5FE',
      100: '#B3E5FC',
      500: '#03A9F4',
      700: '#0277BD',
      900: '#01579B',
    },
    neutral: {
      50: '#FAFAFA',
      100: '#F5F5F5',
      200: '#EEEEEE',
      300: '#E0E0E0',
      400: '#BDBDBD',
      500: '#9E9E9E',
      600: '#757575',
      700: '#616161',
      800: '#424242',
      900: '#212121',
      white: '#FFFFFF',
      black: '#000000',
    },
  },

  // ==================== Typography ====================
  typography: {
    fontFamily: {
      primary: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      heading: "'Poppins', 'Helvetica Neue', Arial, sans-serif",
      mono: "'Fira Code', 'Courier New', monospace",
    },
    fontSize: {
      xs: '0.75rem',      // 12px
      sm: '0.875rem',     // 14px
      base: '1rem',       // 16px
      lg: '1.125rem',     // 18px
      xl: '1.25rem',      // 20px
      '2xl': '1.5rem',    // 24px
      '3xl': '1.875rem',  // 30px
      '4xl': '2.25rem',   // 36px
      '5xl': '3rem',      // 48px
      '6xl': '3.75rem',   // 60px
      '7xl': '4.5rem',    // 72px
    },
    fontWeight: {
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    lineHeight: {
      tight: 1.25,
      normal: 1.5,
      relaxed: 1.75,
      loose: 2,
    },
    letterSpacing: {
      tight: '-0.05em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
  },

  // ==================== Spacing ====================
  spacing: {
    0: '0',
    1: '0.25rem',   // 4px
    2: '0.5rem',    // 8px
    3: '0.75rem',   // 12px
    4: '1rem',      // 16px
    5: '1.25rem',   // 20px
    6: '1.5rem',    // 24px
    8: '2rem',      // 32px
    10: '2.5rem',   // 40px
    12: '3rem',     // 48px
    16: '4rem',     // 64px
    20: '5rem',     // 80px
    24: '6rem',     // 96px
  },

  // ==================== Border Radius ====================
  borderRadius: {
    none: '0',
    sm: '0.125rem',   // 2px
    md: '0.375rem',   // 6px
    lg: '0.5rem',     // 8px
    xl: '0.75rem',    // 12px
    '2xl': '1rem',    // 16px
    '3xl': '1.5rem',  // 24px
    full: '9999px',
  },

  // ==================== Shadows ====================
  shadows: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    none: 'none',
  },

  // ==================== Breakpoints ====================
  breakpoints: {
    xs: '320px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },

  // ==================== Animations ====================
  animations: {
    duration: {
      fast: '150ms',
      normal: '300ms',
      slow: '500ms',
    },
    easing: {
      linear: 'linear',
      easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
      easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
      easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
  },

  // ==================== Component Tokens ====================
  components: {
    button: {
      height: {
        sm: '32px',
        md: '40px',
        lg: '48px',
      },
      padding: {
        sm: '8px 16px',
        md: '12px 24px',
        lg: '16px 32px',
      },
      borderRadius: '8px',
    },
    input: {
      height: {
        sm: '36px',
        md: '44px',
        lg: '52px',
      },
      borderWidth: '1px',
      borderRadius: '6px',
    },
    card: {
      padding: '24px',
      borderRadius: '12px',
      shadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    },
  },

  // ==================== Z-Index ====================
  zIndex: {
    dropdown: 1000,
    sticky: 1020,
    fixed: 1030,
    modalBackdrop: 1040,
    modal: 1050,
    popover: 1060,
    tooltip: 1070,
  },

  // ==================== Accessibility ====================
  accessibility: {
    focusRingWidth: '3px',
    focusRingColor: '#2196F3',
    focusRingOffset: '2px',
    minimumContrastRatio: 4.5,
    largeTextContrastRatio: 3,
  },
};

// ==================== Theme Variants ====================
export const themes = {
  light: {
    background: {
      primary: designSystem.colors.neutral.white,
      secondary: designSystem.colors.neutral[50],
      tertiary: designSystem.colors.neutral[100],
    },
    text: {
      primary: designSystem.colors.neutral[900],
      secondary: designSystem.colors.neutral[700],
      disabled: designSystem.colors.neutral[400],
      inverse: designSystem.colors.neutral.white,
    },
    border: {
      default: designSystem.colors.neutral[300],
      light: designSystem.colors.neutral[200],
      dark: designSystem.colors.neutral[400],
    },
  },
  dark: {
    background: {
      primary: designSystem.colors.neutral[900],
      secondary: designSystem.colors.neutral[800],
      tertiary: designSystem.colors.neutral[700],
    },
    text: {
      primary: designSystem.colors.neutral.white,
      secondary: designSystem.colors.neutral[300],
      disabled: designSystem.colors.neutral[600],
      inverse: designSystem.colors.neutral[900],
    },
    border: {
      default: designSystem.colors.neutral[700],
      light: designSystem.colors.neutral[800],
      dark: designSystem.colors.neutral[600],
    },
  },
};

export default designSystem;
