/**
 * Market-Specific Presets
 *
 * Pre-configured assumptions for 50+ major US markets including:
 * - Property tax rates
 * - Insurance rates
 * - Rent growth projections
 * - Appreciation rates
 * - Vacancy rates
 * - Cap rates
 * - And more market-specific metrics
 */

export interface MarketPreset {
  id: string;
  name: string;
  state: string;
  region: string;

  // Tax & Insurance
  propertyTaxRate: number;        // Annual property tax as % of property value
  insuranceRate: number;          // Annual insurance as % of property value
  transferTaxRate: number;        // One-time transfer/recording tax on purchase

  // Growth Rates
  rentGrowthRate: number;         // Annual rent growth %
  appreciationRate: number;       // Annual property value appreciation %
  populationGrowthRate: number;   // Annual population growth %

  // Market Metrics
  vacancyRate: number;            // Typical vacancy rate %
  capRate: number;                // Market cap rate for multifamily %
  priceToRentRatio: number;       // Median home price / annual rent

  // Operating Expenses
  managementFeeRate: number;      // Property management fee as % of gross income
  maintenanceRate: number;        // Annual maintenance as % of property value
  utilitiesRate: number;          // Monthly utilities cost estimate (if landlord-paid)

  // Market Characteristics
  medianHomePrice: number;        // Median home price
  medianRent: number;             // Median monthly rent
  daysOnMarket: number;           // Average days on market
  inventoryMonths: number;        // Months of housing inventory

  // Economic Indicators
  unemploymentRate: number;       // Local unemployment rate %
  medianIncome: number;           // Median household income
  jobGrowthRate: number;          // Annual job growth %

  // Notes
  notes?: string;
  lastUpdated: string;
}

export const MARKET_PRESETS: MarketPreset[] = [
  // FLORIDA MARKETS
  {
    id: 'miami-fl',
    name: 'Miami',
    state: 'Florida',
    region: 'Southeast',
    propertyTaxRate: 2.5,
    insuranceRate: 6.0,
    transferTaxRate: 0.7,
    rentGrowthRate: 5.0,
    appreciationRate: 6.5,
    populationGrowthRate: 2.1,
    vacancyRate: 6.5,
    capRate: 5.5,
    priceToRentRatio: 18.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.5,
    utilitiesRate: 250,
    medianHomePrice: 565000,
    medianRent: 2800,
    daysOnMarket: 45,
    inventoryMonths: 3.2,
    unemploymentRate: 2.8,
    medianIncome: 68500,
    jobGrowthRate: 3.5,
    notes: 'Strong international demand, high insurance due to hurricane risk',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'tampa-fl',
    name: 'Tampa',
    state: 'Florida',
    region: 'Southeast',
    propertyTaxRate: 2.3,
    insuranceRate: 5.5,
    transferTaxRate: 0.7,
    rentGrowthRate: 6.5,
    appreciationRate: 7.2,
    populationGrowthRate: 2.8,
    vacancyRate: 5.5,
    capRate: 5.8,
    priceToRentRatio: 16.8,
    managementFeeRate: 8.0,
    maintenanceRate: 1.4,
    utilitiesRate: 230,
    medianHomePrice: 425000,
    medianRent: 2100,
    daysOnMarket: 38,
    inventoryMonths: 2.8,
    unemploymentRate: 2.5,
    medianIncome: 62000,
    jobGrowthRate: 4.2,
    notes: 'Rapid growth market, strong job creation',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'orlando-fl',
    name: 'Orlando',
    state: 'Florida',
    region: 'Southeast',
    propertyTaxRate: 2.4,
    insuranceRate: 5.0,
    transferTaxRate: 0.7,
    rentGrowthRate: 5.8,
    appreciationRate: 6.8,
    populationGrowthRate: 2.5,
    vacancyRate: 6.0,
    capRate: 6.0,
    priceToRentRatio: 17.2,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 220,
    medianHomePrice: 385000,
    medianRent: 1950,
    daysOnMarket: 42,
    inventoryMonths: 3.0,
    unemploymentRate: 2.9,
    medianIncome: 58000,
    jobGrowthRate: 3.8,
    notes: 'Tourism-driven economy, strong rental demand',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'jacksonville-fl',
    name: 'Jacksonville',
    state: 'Florida',
    region: 'Southeast',
    propertyTaxRate: 2.2,
    insuranceRate: 4.5,
    transferTaxRate: 0.7,
    rentGrowthRate: 5.2,
    appreciationRate: 6.0,
    populationGrowthRate: 2.0,
    vacancyRate: 5.8,
    capRate: 6.2,
    priceToRentRatio: 16.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 210,
    medianHomePrice: 325000,
    medianRent: 1650,
    daysOnMarket: 48,
    inventoryMonths: 3.5,
    unemploymentRate: 3.0,
    medianIncome: 61000,
    jobGrowthRate: 3.2,
    notes: 'Affordable Florida market, strong logistics sector',
    lastUpdated: '2024-06-01',
  },

  // TEXAS MARKETS
  {
    id: 'austin-tx',
    name: 'Austin',
    state: 'Texas',
    region: 'Southwest',
    propertyTaxRate: 1.8,
    insuranceRate: 3.0,
    transferTaxRate: 0.0,
    rentGrowthRate: 8.0,
    appreciationRate: 9.5,
    populationGrowthRate: 3.2,
    vacancyRate: 5.2,
    capRate: 5.2,
    priceToRentRatio: 19.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 195,
    medianHomePrice: 575000,
    medianRent: 2400,
    daysOnMarket: 35,
    inventoryMonths: 2.5,
    unemploymentRate: 2.3,
    medianIncome: 85000,
    jobGrowthRate: 5.5,
    notes: 'Tech hub, explosive growth, high demand',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'dallas-tx',
    name: 'Dallas',
    state: 'Texas',
    region: 'Southwest',
    propertyTaxRate: 1.9,
    insuranceRate: 3.2,
    transferTaxRate: 0.0,
    rentGrowthRate: 6.5,
    appreciationRate: 7.8,
    populationGrowthRate: 2.5,
    vacancyRate: 6.0,
    capRate: 5.8,
    priceToRentRatio: 17.8,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 200,
    medianHomePrice: 425000,
    medianRent: 1950,
    daysOnMarket: 40,
    inventoryMonths: 3.0,
    unemploymentRate: 2.6,
    medianIncome: 72000,
    jobGrowthRate: 4.0,
    notes: 'Major corporate relocations, diverse economy',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'houston-tx',
    name: 'Houston',
    state: 'Texas',
    region: 'Southwest',
    propertyTaxRate: 2.0,
    insuranceRate: 3.5,
    transferTaxRate: 0.0,
    rentGrowthRate: 5.5,
    appreciationRate: 6.2,
    populationGrowthRate: 2.2,
    vacancyRate: 6.5,
    capRate: 6.5,
    priceToRentRatio: 16.2,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 210,
    medianHomePrice: 325000,
    medianRent: 1650,
    daysOnMarket: 50,
    inventoryMonths: 3.8,
    unemploymentRate: 3.5,
    medianIncome: 65000,
    jobGrowthRate: 3.0,
    notes: 'Energy sector hub, affordable relative to size',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'san-antonio-tx',
    name: 'San Antonio',
    state: 'Texas',
    region: 'Southwest',
    propertyTaxRate: 1.7,
    insuranceRate: 2.8,
    transferTaxRate: 0.0,
    rentGrowthRate: 5.0,
    appreciationRate: 5.8,
    populationGrowthRate: 2.0,
    vacancyRate: 6.2,
    capRate: 6.8,
    priceToRentRatio: 15.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.1,
    utilitiesRate: 185,
    medianHomePrice: 285000,
    medianRent: 1550,
    daysOnMarket: 52,
    inventoryMonths: 4.0,
    unemploymentRate: 3.2,
    medianIncome: 58000,
    jobGrowthRate: 2.8,
    notes: 'Military presence, affordable market',
    lastUpdated: '2024-06-01',
  },

  // CALIFORNIA MARKETS
  {
    id: 'los-angeles-ca',
    name: 'Los Angeles',
    state: 'California',
    region: 'West',
    propertyTaxRate: 1.2,
    insuranceRate: 1.8,
    transferTaxRate: 0.55,
    rentGrowthRate: 4.5,
    appreciationRate: 5.5,
    populationGrowthRate: 0.5,
    vacancyRate: 5.0,
    capRate: 4.5,
    priceToRentRatio: 25.5,
    managementFeeRate: 7.0,
    maintenanceRate: 1.4,
    utilitiesRate: 180,
    medianHomePrice: 875000,
    medianRent: 2850,
    daysOnMarket: 38,
    inventoryMonths: 2.8,
    unemploymentRate: 4.5,
    medianIncome: 78000,
    jobGrowthRate: 1.8,
    notes: 'Prop 13 caps tax increases, high entry cost',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'san-francisco-ca',
    name: 'San Francisco',
    state: 'California',
    region: 'West',
    propertyTaxRate: 1.2,
    insuranceRate: 1.5,
    transferTaxRate: 2.75,
    rentGrowthRate: 3.5,
    appreciationRate: 4.8,
    populationGrowthRate: -0.5,
    vacancyRate: 6.5,
    capRate: 3.8,
    priceToRentRatio: 28.5,
    managementFeeRate: 7.0,
    maintenanceRate: 1.6,
    utilitiesRate: 150,
    medianHomePrice: 1350000,
    medianRent: 3850,
    daysOnMarket: 32,
    inventoryMonths: 2.2,
    unemploymentRate: 3.8,
    medianIncome: 125000,
    jobGrowthRate: 0.5,
    notes: 'Tech hub, rent control laws, high transfer taxes',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'san-diego-ca',
    name: 'San Diego',
    state: 'California',
    region: 'West',
    propertyTaxRate: 1.1,
    insuranceRate: 1.6,
    transferTaxRate: 0.55,
    rentGrowthRate: 4.8,
    appreciationRate: 6.0,
    populationGrowthRate: 0.8,
    vacancyRate: 4.5,
    capRate: 4.8,
    priceToRentRatio: 24.0,
    managementFeeRate: 7.0,
    maintenanceRate: 1.3,
    utilitiesRate: 170,
    medianHomePrice: 925000,
    medianRent: 3200,
    daysOnMarket: 35,
    inventoryMonths: 2.5,
    unemploymentRate: 3.5,
    medianIncome: 88000,
    jobGrowthRate: 2.2,
    notes: 'Strong military presence, limited inventory',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'sacramento-ca',
    name: 'Sacramento',
    state: 'California',
    region: 'West',
    propertyTaxRate: 1.1,
    insuranceRate: 1.4,
    transferTaxRate: 0.55,
    rentGrowthRate: 5.2,
    appreciationRate: 6.5,
    populationGrowthRate: 1.2,
    vacancyRate: 5.5,
    capRate: 5.2,
    priceToRentRatio: 21.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 165,
    medianHomePrice: 485000,
    medianRent: 1900,
    daysOnMarket: 42,
    inventoryMonths: 3.2,
    unemploymentRate: 4.0,
    medianIncome: 72000,
    jobGrowthRate: 2.5,
    notes: 'Bay Area spillover, state capital',
    lastUpdated: '2024-06-01',
  },

  // NEW YORK / NORTHEAST
  {
    id: 'new-york-ny',
    name: 'New York City',
    state: 'New York',
    region: 'Northeast',
    propertyTaxRate: 4.0,
    insuranceRate: 2.0,
    transferTaxRate: 2.0,
    rentGrowthRate: 3.0,
    appreciationRate: 4.0,
    populationGrowthRate: 0.2,
    vacancyRate: 5.5,
    capRate: 4.2,
    priceToRentRatio: 26.0,
    managementFeeRate: 6.0,
    maintenanceRate: 2.0,
    utilitiesRate: 200,
    medianHomePrice: 785000,
    medianRent: 3500,
    daysOnMarket: 55,
    inventoryMonths: 4.5,
    unemploymentRate: 5.2,
    medianIncome: 75000,
    jobGrowthRate: 1.0,
    notes: 'Rent stabilization laws, high property taxes, mansion tax',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'boston-ma',
    name: 'Boston',
    state: 'Massachusetts',
    region: 'Northeast',
    propertyTaxRate: 1.8,
    insuranceRate: 2.2,
    transferTaxRate: 0.456,
    rentGrowthRate: 4.0,
    appreciationRate: 5.0,
    populationGrowthRate: 0.5,
    vacancyRate: 4.5,
    capRate: 4.5,
    priceToRentRatio: 24.5,
    managementFeeRate: 7.0,
    maintenanceRate: 1.8,
    utilitiesRate: 220,
    medianHomePrice: 725000,
    medianRent: 3200,
    daysOnMarket: 45,
    inventoryMonths: 3.5,
    unemploymentRate: 3.2,
    medianIncome: 95000,
    jobGrowthRate: 1.5,
    notes: 'Strong education/healthcare sectors, limited supply',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'philadelphia-pa',
    name: 'Philadelphia',
    state: 'Pennsylvania',
    region: 'Northeast',
    propertyTaxRate: 2.8,
    insuranceRate: 1.8,
    transferTaxRate: 4.0,
    rentGrowthRate: 4.2,
    appreciationRate: 4.5,
    populationGrowthRate: 0.3,
    vacancyRate: 6.5,
    capRate: 6.0,
    priceToRentRatio: 18.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.6,
    utilitiesRate: 190,
    medianHomePrice: 285000,
    medianRent: 1650,
    daysOnMarket: 50,
    inventoryMonths: 4.0,
    unemploymentRate: 5.8,
    medianIncome: 52000,
    jobGrowthRate: 1.2,
    notes: 'High transfer tax, affordable relative to Northeast',
    lastUpdated: '2024-06-01',
  },

  // ARIZONA
  {
    id: 'phoenix-az',
    name: 'Phoenix',
    state: 'Arizona',
    region: 'Southwest',
    propertyTaxRate: 1.5,
    insuranceRate: 2.5,
    transferTaxRate: 0.0,
    rentGrowthRate: 7.5,
    appreciationRate: 8.5,
    populationGrowthRate: 2.8,
    vacancyRate: 5.5,
    capRate: 5.5,
    priceToRentRatio: 18.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 205,
    medianHomePrice: 465000,
    medianRent: 2100,
    daysOnMarket: 38,
    inventoryMonths: 2.8,
    unemploymentRate: 3.2,
    medianIncome: 68000,
    jobGrowthRate: 4.5,
    notes: 'Rapid growth, tech sector expansion, semiconductor manufacturing',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'tucson-az',
    name: 'Tucson',
    state: 'Arizona',
    region: 'Southwest',
    propertyTaxRate: 1.4,
    insuranceRate: 2.2,
    transferTaxRate: 0.0,
    rentGrowthRate: 5.5,
    appreciationRate: 6.0,
    populationGrowthRate: 1.5,
    vacancyRate: 6.5,
    capRate: 6.5,
    priceToRentRatio: 16.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.1,
    utilitiesRate: 185,
    medianHomePrice: 315000,
    medianRent: 1550,
    daysOnMarket: 48,
    inventoryMonths: 3.5,
    unemploymentRate: 3.8,
    medianIncome: 55000,
    jobGrowthRate: 2.5,
    notes: 'University town, more affordable than Phoenix',
    lastUpdated: '2024-06-01',
  },

  // COLORADO
  {
    id: 'denver-co',
    name: 'Denver',
    state: 'Colorado',
    region: 'Mountain West',
    propertyTaxRate: 1.5,
    insuranceRate: 2.0,
    transferTaxRate: 0.01,
    rentGrowthRate: 6.0,
    appreciationRate: 7.0,
    populationGrowthRate: 1.8,
    vacancyRate: 5.0,
    capRate: 5.5,
    priceToRentRatio: 20.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 175,
    medianHomePrice: 625000,
    medianRent: 2550,
    daysOnMarket: 40,
    inventoryMonths: 3.0,
    unemploymentRate: 2.8,
    medianIncome: 85000,
    jobGrowthRate: 3.5,
    notes: 'Strong tech sector, quality of life premium',
    lastUpdated: '2024-06-01',
  },

  // NEVADA
  {
    id: 'las-vegas-nv',
    name: 'Las Vegas',
    state: 'Nevada',
    region: 'Southwest',
    propertyTaxRate: 1.6,
    insuranceRate: 2.2,
    transferTaxRate: 0.0,
    rentGrowthRate: 7.0,
    appreciationRate: 8.0,
    populationGrowthRate: 2.5,
    vacancyRate: 6.0,
    capRate: 6.0,
    priceToRentRatio: 17.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 180,
    medianHomePrice: 425000,
    medianRent: 2000,
    daysOnMarket: 42,
    inventoryMonths: 3.2,
    unemploymentRate: 4.8,
    medianIncome: 62000,
    jobGrowthRate: 3.8,
    notes: 'No state income tax, tourism-driven economy',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'reno-nv',
    name: 'Reno',
    state: 'Nevada',
    region: 'West',
    propertyTaxRate: 1.5,
    insuranceRate: 2.0,
    transferTaxRate: 0.0,
    rentGrowthRate: 6.5,
    appreciationRate: 7.5,
    populationGrowthRate: 2.2,
    vacancyRate: 5.5,
    capRate: 6.2,
    priceToRentRatio: 18.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.1,
    utilitiesRate: 170,
    medianHomePrice: 515000,
    medianRent: 2350,
    daysOnMarket: 38,
    inventoryMonths: 2.8,
    unemploymentRate: 3.5,
    medianIncome: 72000,
    jobGrowthRate: 4.0,
    notes: 'Tesla Gigafactory impact, tech sector growth',
    lastUpdated: '2024-06-01',
  },

  // WASHINGTON
  {
    id: 'seattle-wa',
    name: 'Seattle',
    state: 'Washington',
    region: 'Northwest',
    propertyTaxRate: 1.8,
    insuranceRate: 1.5,
    transferTaxRate: 1.78,
    rentGrowthRate: 5.5,
    appreciationRate: 6.5,
    populationGrowthRate: 1.5,
    vacancyRate: 5.0,
    capRate: 4.8,
    priceToRentRatio: 22.0,
    managementFeeRate: 7.0,
    maintenanceRate: 1.4,
    utilitiesRate: 160,
    medianHomePrice: 825000,
    medianRent: 3050,
    daysOnMarket: 35,
    inventoryMonths: 2.5,
    unemploymentRate: 3.5,
    medianIncome: 105000,
    jobGrowthRate: 2.5,
    notes: 'Tech hub, no state income tax, strong job market',
    lastUpdated: '2024-06-01',
  },

  // OREGON
  {
    id: 'portland-or',
    name: 'Portland',
    state: 'Oregon',
    region: 'Northwest',
    propertyTaxRate: 1.7,
    insuranceRate: 1.6,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.5,
    appreciationRate: 5.5,
    populationGrowthRate: 0.8,
    vacancyRate: 5.8,
    capRate: 5.5,
    priceToRentRatio: 21.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 155,
    medianHomePrice: 565000,
    medianRent: 2200,
    daysOnMarket: 45,
    inventoryMonths: 3.5,
    unemploymentRate: 3.8,
    medianIncome: 78000,
    jobGrowthRate: 1.8,
    notes: 'Strong rental regulations, urban growth boundary',
    lastUpdated: '2024-06-01',
  },

  // UTAH
  {
    id: 'salt-lake-city-ut',
    name: 'Salt Lake City',
    state: 'Utah',
    region: 'Mountain West',
    propertyTaxRate: 1.3,
    insuranceRate: 1.8,
    transferTaxRate: 0.0,
    rentGrowthRate: 6.5,
    appreciationRate: 7.5,
    populationGrowthRate: 2.0,
    vacancyRate: 4.8,
    capRate: 5.8,
    priceToRentRatio: 19.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 165,
    medianHomePrice: 535000,
    medianRent: 2300,
    daysOnMarket: 35,
    inventoryMonths: 2.2,
    unemploymentRate: 2.5,
    medianIncome: 78000,
    jobGrowthRate: 3.8,
    notes: 'Fast-growing tech scene, "Silicon Slopes"',
    lastUpdated: '2024-06-01',
  },

  // TENNESSEE
  {
    id: 'nashville-tn',
    name: 'Nashville',
    state: 'Tennessee',
    region: 'Southeast',
    propertyTaxRate: 1.5,
    insuranceRate: 2.5,
    transferTaxRate: 0.37,
    rentGrowthRate: 7.0,
    appreciationRate: 8.0,
    populationGrowthRate: 2.5,
    vacancyRate: 5.5,
    capRate: 5.5,
    priceToRentRatio: 18.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 195,
    medianHomePrice: 485000,
    medianRent: 2150,
    daysOnMarket: 38,
    inventoryMonths: 2.8,
    unemploymentRate: 2.8,
    medianIncome: 72000,
    jobGrowthRate: 4.0,
    notes: 'No state income tax, major corporate relocations',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'memphis-tn',
    name: 'Memphis',
    state: 'Tennessee',
    region: 'Southeast',
    propertyTaxRate: 2.8,
    insuranceRate: 2.8,
    transferTaxRate: 0.37,
    rentGrowthRate: 4.5,
    appreciationRate: 4.8,
    populationGrowthRate: 0.5,
    vacancyRate: 7.5,
    capRate: 7.5,
    priceToRentRatio: 14.0,
    managementFeeRate: 9.0,
    maintenanceRate: 1.4,
    utilitiesRate: 180,
    medianHomePrice: 225000,
    medianRent: 1350,
    daysOnMarket: 58,
    inventoryMonths: 4.5,
    unemploymentRate: 5.5,
    medianIncome: 48000,
    jobGrowthRate: 1.5,
    notes: 'Logistics hub, affordable cash flow market',
    lastUpdated: '2024-06-01',
  },

  // NORTH CAROLINA
  {
    id: 'charlotte-nc',
    name: 'Charlotte',
    state: 'North Carolina',
    region: 'Southeast',
    propertyTaxRate: 1.5,
    insuranceRate: 2.2,
    transferTaxRate: 0.2,
    rentGrowthRate: 6.0,
    appreciationRate: 6.8,
    populationGrowthRate: 2.2,
    vacancyRate: 5.5,
    capRate: 5.8,
    priceToRentRatio: 17.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 185,
    medianHomePrice: 425000,
    medianRent: 2000,
    daysOnMarket: 42,
    inventoryMonths: 3.0,
    unemploymentRate: 3.2,
    medianIncome: 72000,
    jobGrowthRate: 3.5,
    notes: 'Banking hub, strong job growth',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'raleigh-nc',
    name: 'Raleigh',
    state: 'North Carolina',
    region: 'Southeast',
    propertyTaxRate: 1.4,
    insuranceRate: 2.0,
    transferTaxRate: 0.2,
    rentGrowthRate: 6.5,
    appreciationRate: 7.2,
    populationGrowthRate: 2.5,
    vacancyRate: 5.0,
    capRate: 5.5,
    priceToRentRatio: 18.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 180,
    medianHomePrice: 465000,
    medianRent: 2150,
    daysOnMarket: 38,
    inventoryMonths: 2.8,
    unemploymentRate: 2.8,
    medianIncome: 75000,
    jobGrowthRate: 4.0,
    notes: 'Research Triangle, strong tech sector',
    lastUpdated: '2024-06-01',
  },

  // GEORGIA
  {
    id: 'atlanta-ga',
    name: 'Atlanta',
    state: 'Georgia',
    region: 'Southeast',
    propertyTaxRate: 1.8,
    insuranceRate: 2.5,
    transferTaxRate: 0.1,
    rentGrowthRate: 5.8,
    appreciationRate: 6.5,
    populationGrowthRate: 2.0,
    vacancyRate: 6.0,
    capRate: 6.0,
    priceToRentRatio: 17.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 195,
    medianHomePrice: 385000,
    medianRent: 1900,
    daysOnMarket: 45,
    inventoryMonths: 3.2,
    unemploymentRate: 3.5,
    medianIncome: 68000,
    jobGrowthRate: 3.2,
    notes: 'Major corporate HQs, film industry growth',
    lastUpdated: '2024-06-01',
  },

  // ILLINOIS
  {
    id: 'chicago-il',
    name: 'Chicago',
    state: 'Illinois',
    region: 'Midwest',
    propertyTaxRate: 3.5,
    insuranceRate: 2.0,
    transferTaxRate: 0.75,
    rentGrowthRate: 3.5,
    appreciationRate: 4.0,
    populationGrowthRate: -0.2,
    vacancyRate: 6.5,
    capRate: 6.5,
    priceToRentRatio: 16.5,
    managementFeeRate: 7.0,
    maintenanceRate: 1.5,
    utilitiesRate: 175,
    medianHomePrice: 325000,
    medianRent: 2100,
    daysOnMarket: 55,
    inventoryMonths: 4.2,
    unemploymentRate: 4.5,
    medianIncome: 68000,
    jobGrowthRate: 0.8,
    notes: 'High property taxes, diverse economy',
    lastUpdated: '2024-06-01',
  },

  // MICHIGAN
  {
    id: 'detroit-mi',
    name: 'Detroit',
    state: 'Michigan',
    region: 'Midwest',
    propertyTaxRate: 3.0,
    insuranceRate: 2.5,
    transferTaxRate: 0.75,
    rentGrowthRate: 4.0,
    appreciationRate: 4.5,
    populationGrowthRate: 0.2,
    vacancyRate: 8.0,
    capRate: 8.0,
    priceToRentRatio: 13.5,
    managementFeeRate: 9.0,
    maintenanceRate: 1.6,
    utilitiesRate: 165,
    medianHomePrice: 185000,
    medianRent: 1150,
    daysOnMarket: 65,
    inventoryMonths: 5.0,
    unemploymentRate: 6.0,
    medianIncome: 52000,
    jobGrowthRate: 1.0,
    notes: 'Manufacturing base, urban revitalization',
    lastUpdated: '2024-06-01',
  },

  // OHIO
  {
    id: 'columbus-oh',
    name: 'Columbus',
    state: 'Ohio',
    region: 'Midwest',
    propertyTaxRate: 2.5,
    insuranceRate: 1.8,
    transferTaxRate: 0.0,
    rentGrowthRate: 5.0,
    appreciationRate: 5.5,
    populationGrowthRate: 1.5,
    vacancyRate: 6.0,
    capRate: 6.5,
    priceToRentRatio: 15.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 170,
    medianHomePrice: 285000,
    medianRent: 1550,
    daysOnMarket: 48,
    inventoryMonths: 3.5,
    unemploymentRate: 3.5,
    medianIncome: 62000,
    jobGrowthRate: 2.5,
    notes: 'State capital, Ohio State University impact',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'cleveland-oh',
    name: 'Cleveland',
    state: 'Ohio',
    region: 'Midwest',
    propertyTaxRate: 2.8,
    insuranceRate: 2.0,
    transferTaxRate: 0.0,
    rentGrowthRate: 3.8,
    appreciationRate: 4.0,
    populationGrowthRate: 0.0,
    vacancyRate: 7.0,
    capRate: 7.5,
    priceToRentRatio: 14.0,
    managementFeeRate: 8.5,
    maintenanceRate: 1.5,
    utilitiesRate: 175,
    medianHomePrice: 195000,
    medianRent: 1200,
    daysOnMarket: 60,
    inventoryMonths: 4.8,
    unemploymentRate: 5.0,
    medianIncome: 55000,
    jobGrowthRate: 0.8,
    notes: 'Healthcare sector, affordable market',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'cincinnati-oh',
    name: 'Cincinnati',
    state: 'Ohio',
    region: 'Midwest',
    propertyTaxRate: 2.6,
    insuranceRate: 1.9,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.5,
    appreciationRate: 5.0,
    populationGrowthRate: 0.8,
    vacancyRate: 6.5,
    capRate: 7.0,
    priceToRentRatio: 14.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.4,
    utilitiesRate: 172,
    medianHomePrice: 245000,
    medianRent: 1400,
    daysOnMarket: 52,
    inventoryMonths: 4.0,
    unemploymentRate: 4.2,
    medianIncome: 58000,
    jobGrowthRate: 1.5,
    notes: 'Major corporate presence, affordable Midwest market',
    lastUpdated: '2024-06-01',
  },

  // MINNESOTA
  {
    id: 'minneapolis-mn',
    name: 'Minneapolis',
    state: 'Minnesota',
    region: 'Midwest',
    propertyTaxRate: 2.2,
    insuranceRate: 1.8,
    transferTaxRate: 0.33,
    rentGrowthRate: 4.5,
    appreciationRate: 5.0,
    populationGrowthRate: 1.0,
    vacancyRate: 5.5,
    capRate: 6.0,
    priceToRentRatio: 17.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.4,
    utilitiesRate: 185,
    medianHomePrice: 385000,
    medianRent: 1900,
    daysOnMarket: 48,
    inventoryMonths: 3.5,
    unemploymentRate: 3.0,
    medianIncome: 75000,
    jobGrowthRate: 2.0,
    notes: 'Strong economy, Fortune 500 companies',
    lastUpdated: '2024-06-01',
  },

  // WISCONSIN
  {
    id: 'milwaukee-wi',
    name: 'Milwaukee',
    state: 'Wisconsin',
    region: 'Midwest',
    propertyTaxRate: 2.5,
    insuranceRate: 1.7,
    transferTaxRate: 0.3,
    rentGrowthRate: 4.0,
    appreciationRate: 4.5,
    populationGrowthRate: 0.5,
    vacancyRate: 6.5,
    capRate: 6.8,
    priceToRentRatio: 15.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.4,
    utilitiesRate: 180,
    medianHomePrice: 265000,
    medianRent: 1450,
    daysOnMarket: 55,
    inventoryMonths: 4.0,
    unemploymentRate: 4.0,
    medianIncome: 58000,
    jobGrowthRate: 1.2,
    notes: 'Manufacturing base, affordable market',
    lastUpdated: '2024-06-01',
  },

  // MISSOURI
  {
    id: 'kansas-city-mo',
    name: 'Kansas City',
    state: 'Missouri',
    region: 'Midwest',
    propertyTaxRate: 2.0,
    insuranceRate: 2.0,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.8,
    appreciationRate: 5.2,
    populationGrowthRate: 1.2,
    vacancyRate: 6.0,
    capRate: 6.8,
    priceToRentRatio: 15.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 175,
    medianHomePrice: 285000,
    medianRent: 1600,
    daysOnMarket: 50,
    inventoryMonths: 3.8,
    unemploymentRate: 3.8,
    medianIncome: 62000,
    jobGrowthRate: 2.0,
    notes: 'Affordable, strong cash flow market',
    lastUpdated: '2024-06-01',
  },
  {
    id: 'st-louis-mo',
    name: 'St. Louis',
    state: 'Missouri',
    region: 'Midwest',
    propertyTaxRate: 2.2,
    insuranceRate: 2.1,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.0,
    appreciationRate: 4.2,
    populationGrowthRate: 0.3,
    vacancyRate: 7.0,
    capRate: 7.5,
    priceToRentRatio: 14.0,
    managementFeeRate: 8.5,
    maintenanceRate: 1.4,
    utilitiesRate: 170,
    medianHomePrice: 235000,
    medianRent: 1400,
    daysOnMarket: 58,
    inventoryMonths: 4.5,
    unemploymentRate: 4.5,
    medianIncome: 56000,
    jobGrowthRate: 1.0,
    notes: 'Affordable prices, strong rental yields',
    lastUpdated: '2024-06-01',
  },

  // INDIANA
  {
    id: 'indianapolis-in',
    name: 'Indianapolis',
    state: 'Indiana',
    region: 'Midwest',
    propertyTaxRate: 2.0,
    insuranceRate: 1.8,
    transferTaxRate: 0.0,
    rentGrowthRate: 5.0,
    appreciationRate: 5.5,
    populationGrowthRate: 1.2,
    vacancyRate: 6.2,
    capRate: 7.0,
    priceToRentRatio: 14.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 168,
    medianHomePrice: 265000,
    medianRent: 1550,
    daysOnMarket: 48,
    inventoryMonths: 3.8,
    unemploymentRate: 3.5,
    medianIncome: 60000,
    jobGrowthRate: 2.2,
    notes: 'Logistics hub, affordable with good cash flow',
    lastUpdated: '2024-06-01',
  },

  // LOUISIANA
  {
    id: 'new-orleans-la',
    name: 'New Orleans',
    state: 'Louisiana',
    region: 'Southeast',
    propertyTaxRate: 1.5,
    insuranceRate: 5.5,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.5,
    appreciationRate: 5.0,
    populationGrowthRate: 0.8,
    vacancyRate: 7.5,
    capRate: 7.0,
    priceToRentRatio: 15.5,
    managementFeeRate: 9.0,
    maintenanceRate: 1.8,
    utilitiesRate: 220,
    medianHomePrice: 285000,
    medianRent: 1550,
    daysOnMarket: 55,
    inventoryMonths: 4.5,
    unemploymentRate: 4.8,
    medianIncome: 52000,
    jobGrowthRate: 1.5,
    notes: 'High insurance due to hurricane risk, strong tourism',
    lastUpdated: '2024-06-01',
  },

  // SOUTH CAROLINA
  {
    id: 'charleston-sc',
    name: 'Charleston',
    state: 'South Carolina',
    region: 'Southeast',
    propertyTaxRate: 1.6,
    insuranceRate: 4.0,
    transferTaxRate: 0.185,
    rentGrowthRate: 6.0,
    appreciationRate: 6.8,
    populationGrowthRate: 2.2,
    vacancyRate: 5.5,
    capRate: 5.8,
    priceToRentRatio: 18.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 200,
    medianHomePrice: 485000,
    medianRent: 2250,
    daysOnMarket: 40,
    inventoryMonths: 3.0,
    unemploymentRate: 2.8,
    medianIncome: 72000,
    jobGrowthRate: 3.5,
    notes: 'High demand, coastal location, Boeing presence',
    lastUpdated: '2024-06-01',
  },

  // VIRGINIA
  {
    id: 'richmond-va',
    name: 'Richmond',
    state: 'Virginia',
    region: 'Southeast',
    propertyTaxRate: 2.0,
    insuranceRate: 2.0,
    transferTaxRate: 0.25,
    rentGrowthRate: 5.0,
    appreciationRate: 5.5,
    populationGrowthRate: 1.5,
    vacancyRate: 6.0,
    capRate: 6.5,
    priceToRentRatio: 16.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 185,
    medianHomePrice: 345000,
    medianRent: 1750,
    daysOnMarket: 45,
    inventoryMonths: 3.5,
    unemploymentRate: 3.2,
    medianIncome: 68000,
    jobGrowthRate: 2.5,
    notes: 'State capital, healthcare sector growth',
    lastUpdated: '2024-06-01',
  },

  // MARYLAND
  {
    id: 'baltimore-md',
    name: 'Baltimore',
    state: 'Maryland',
    region: 'Northeast',
    propertyTaxRate: 3.0,
    insuranceRate: 2.2,
    transferTaxRate: 1.5,
    rentGrowthRate: 4.0,
    appreciationRate: 4.5,
    populationGrowthRate: 0.0,
    vacancyRate: 7.5,
    capRate: 7.5,
    priceToRentRatio: 14.5,
    managementFeeRate: 8.5,
    maintenanceRate: 1.6,
    utilitiesRate: 195,
    medianHomePrice: 235000,
    medianRent: 1400,
    daysOnMarket: 60,
    inventoryMonths: 4.8,
    unemploymentRate: 5.5,
    medianIncome: 58000,
    jobGrowthRate: 1.0,
    notes: 'High property taxes, healthcare/education sectors',
    lastUpdated: '2024-06-01',
  },

  // OKLAHOMA
  {
    id: 'oklahoma-city-ok',
    name: 'Oklahoma City',
    state: 'Oklahoma',
    region: 'Southwest',
    propertyTaxRate: 1.6,
    insuranceRate: 2.8,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.5,
    appreciationRate: 5.0,
    populationGrowthRate: 1.5,
    vacancyRate: 6.5,
    capRate: 7.5,
    priceToRentRatio: 13.5,
    managementFeeRate: 8.5,
    maintenanceRate: 1.2,
    utilitiesRate: 175,
    medianHomePrice: 225000,
    medianRent: 1400,
    daysOnMarket: 50,
    inventoryMonths: 4.0,
    unemploymentRate: 3.5,
    medianIncome: 58000,
    jobGrowthRate: 2.0,
    notes: 'Energy sector, very affordable',
    lastUpdated: '2024-06-01',
  },

  // KENTUCKY
  {
    id: 'louisville-ky',
    name: 'Louisville',
    state: 'Kentucky',
    region: 'Southeast',
    propertyTaxRate: 1.9,
    insuranceRate: 2.2,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.5,
    appreciationRate: 5.0,
    populationGrowthRate: 1.0,
    vacancyRate: 6.5,
    capRate: 7.0,
    priceToRentRatio: 14.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.3,
    utilitiesRate: 172,
    medianHomePrice: 245000,
    medianRent: 1450,
    daysOnMarket: 52,
    inventoryMonths: 4.2,
    unemploymentRate: 4.0,
    medianIncome: 56000,
    jobGrowthRate: 1.8,
    notes: 'Healthcare and logistics sectors, affordable',
    lastUpdated: '2024-06-01',
  },

  // NEW MEXICO
  {
    id: 'albuquerque-nm',
    name: 'Albuquerque',
    state: 'New Mexico',
    region: 'Southwest',
    propertyTaxRate: 1.4,
    insuranceRate: 2.5,
    transferTaxRate: 0.0,
    rentGrowthRate: 4.8,
    appreciationRate: 5.5,
    populationGrowthRate: 1.2,
    vacancyRate: 6.8,
    capRate: 7.0,
    priceToRentRatio: 15.0,
    managementFeeRate: 8.5,
    maintenanceRate: 1.2,
    utilitiesRate: 165,
    medianHomePrice: 315000,
    medianRent: 1750,
    daysOnMarket: 50,
    inventoryMonths: 4.0,
    unemploymentRate: 4.5,
    medianIncome: 54000,
    jobGrowthRate: 2.0,
    notes: 'Growing tech sector, affordable Southwest market',
    lastUpdated: '2024-06-01',
  },

  // IDAHO
  {
    id: 'boise-id',
    name: 'Boise',
    state: 'Idaho',
    region: 'Mountain West',
    propertyTaxRate: 1.2,
    insuranceRate: 1.5,
    transferTaxRate: 0.0,
    rentGrowthRate: 7.5,
    appreciationRate: 8.5,
    populationGrowthRate: 3.0,
    vacancyRate: 4.8,
    capRate: 5.8,
    priceToRentRatio: 18.5,
    managementFeeRate: 8.0,
    maintenanceRate: 1.1,
    utilitiesRate: 160,
    medianHomePrice: 525000,
    medianRent: 2350,
    daysOnMarket: 32,
    inventoryMonths: 2.2,
    unemploymentRate: 2.5,
    medianIncome: 72000,
    jobGrowthRate: 4.5,
    notes: 'Fastest-growing market, tech sector expansion',
    lastUpdated: '2024-06-01',
  },

  // MONTANA
  {
    id: 'missoula-mt',
    name: 'Missoula',
    state: 'Montana',
    region: 'Mountain West',
    propertyTaxRate: 1.8,
    insuranceRate: 1.6,
    transferTaxRate: 0.0,
    rentGrowthRate: 6.5,
    appreciationRate: 7.0,
    populationGrowthRate: 2.0,
    vacancyRate: 5.0,
    capRate: 6.0,
    priceToRentRatio: 19.0,
    managementFeeRate: 8.0,
    maintenanceRate: 1.2,
    utilitiesRate: 155,
    medianHomePrice: 565000,
    medianRent: 2450,
    daysOnMarket: 38,
    inventoryMonths: 2.8,
    unemploymentRate: 2.8,
    medianIncome: 58000,
    jobGrowthRate: 2.5,
    notes: 'Quality of life premium, limited inventory',
    lastUpdated: '2024-06-01',
  },
];

/**
 * Get market preset by ID
 */
export function getMarketPreset(marketId: string): MarketPreset | undefined {
  return MARKET_PRESETS.find(m => m.id === marketId);
}

/**
 * Get all markets in a specific state
 */
export function getMarketsByState(state: string): MarketPreset[] {
  return MARKET_PRESETS.filter(m => m.state === state);
}

/**
 * Get all markets in a specific region
 */
export function getMarketsByRegion(region: string): MarketPreset[] {
  return MARKET_PRESETS.filter(m => m.region === region);
}

/**
 * Get all unique states
 */
export function getAllStates(): string[] {
  return Array.from(new Set(MARKET_PRESETS.map(m => m.state))).sort();
}

/**
 * Get all unique regions
 */
export function getAllRegions(): string[] {
  return Array.from(new Set(MARKET_PRESETS.map(m => m.region))).sort();
}

/**
 * Compare multiple markets
 */
export function compareMarkets(marketIds: string[]): MarketPreset[] {
  return MARKET_PRESETS.filter(m => marketIds.includes(m.id));
}

/**
 * Find markets matching criteria
 */
export interface MarketSearchCriteria {
  maxPropertyTax?: number;
  minRentGrowth?: number;
  minAppreciation?: number;
  maxVacancy?: number;
  minCapRate?: number;
  maxCapRate?: number;
  maxMedianPrice?: number;
  region?: string;
  state?: string;
}

export function searchMarkets(criteria: MarketSearchCriteria): MarketPreset[] {
  return MARKET_PRESETS.filter(market => {
    if (criteria.maxPropertyTax && market.propertyTaxRate > criteria.maxPropertyTax) return false;
    if (criteria.minRentGrowth && market.rentGrowthRate < criteria.minRentGrowth) return false;
    if (criteria.minAppreciation && market.appreciationRate < criteria.minAppreciation) return false;
    if (criteria.maxVacancy && market.vacancyRate > criteria.maxVacancy) return false;
    if (criteria.minCapRate && market.capRate < criteria.minCapRate) return false;
    if (criteria.maxCapRate && market.capRate > criteria.maxCapRate) return false;
    if (criteria.maxMedianPrice && market.medianHomePrice > criteria.maxMedianPrice) return false;
    if (criteria.region && market.region !== criteria.region) return false;
    if (criteria.state && market.state !== criteria.state) return false;
    return true;
  });
}
