"""
Database Models for Trading Agents

SQLAlchemy models for storing agent configurations, signals, trades, and performance
"""

from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, JSON, Text, ForeignKey, Enum
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from app.models.base import Base


class AgentTypeEnum(enum.Enum):
    """Agent types enumeration"""
    MEAN_REVERSION = "mean_reversion"
    MOMENTUM = "momentum"
    STATISTICAL_ARBITRAGE = "statistical_arbitrage"
    LSTM_PREDICTION = "lstm_prediction"
    REINFORCEMENT_LEARNING = "reinforcement_learning"
    PAIRS_TRADING = "pairs_trading"
    VOLATILITY_ADJUSTED = "volatility_adjusted"
    ENSEMBLE = "ensemble"


class SignalTypeEnum(enum.Enum):
    """Signal types enumeration"""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    STRONG_BUY = "strong_buy"
    STRONG_SELL = "strong_sell"


class TradeStatusEnum(enum.Enum):
    """Trade status enumeration"""
    PENDING = "pending"
    EXECUTED = "executed"
    CANCELLED = "cancelled"
    FAILED = "failed"


class TradingAgent(Base):
    """
    Trading Agent Configuration

    Stores agent instances and their configurations
    """
    __tablename__ = "trading_agents"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(String, unique=True, index=True, nullable=False)
    agent_type = Column(Enum(AgentTypeEnum), nullable=False)
    name = Column(String, nullable=False)
    description = Column(Text)

    # Configuration
    config = Column(JSON, default={})

    # Status
    is_active = Column(Boolean, default=False)
    is_trained = Column(Boolean, default=False)

    # Performance metrics
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    win_rate = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, default=0.0)
    max_drawdown = Column(Float, default=0.0)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    last_signal_at = Column(DateTime)

    # Relationships
    signals = relationship("TradingSignalRecord", back_populates="agent", cascade="all, delete-orphan")
    trades = relationship("Trade", back_populates="agent", cascade="all, delete-orphan")


class TradingSignalRecord(Base):
    """
    Trading Signal Records

    Stores all signals generated by agents
    """
    __tablename__ = "trading_signals"

    id = Column(Integer, primary_key=True, index=True)

    # Agent reference
    agent_id = Column(Integer, ForeignKey("trading_agents.id"), nullable=False)

    # Signal details
    signal_type = Column(Enum(SignalTypeEnum), nullable=False)
    confidence = Column(Float, nullable=False)
    symbol = Column(String, index=True, nullable=False)
    price = Column(Float)
    quantity = Column(Integer)

    # Reasoning and metadata
    reasoning = Column(Text)
    metadata = Column(JSON, default={})

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    # Outcome (filled after trade execution)
    was_executed = Column(Boolean, default=False)
    was_profitable = Column(Boolean)
    actual_pnl = Column(Float)

    # Relationships
    agent = relationship("TradingAgent", back_populates="signals")
    trade = relationship("Trade", back_populates="signal", uselist=False)


class Trade(Base):
    """
    Trade Execution Records

    Stores executed trades
    """
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True)

    # Agent reference
    agent_id = Column(Integer, ForeignKey("trading_agents.id"), nullable=False)

    # Signal reference
    signal_id = Column(Integer, ForeignKey("trading_signals.id"))

    # Trade details
    symbol = Column(String, index=True, nullable=False)
    side = Column(String, nullable=False)  # "buy" or "sell"
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float)

    # Trade status
    status = Column(Enum(TradeStatusEnum), default=TradeStatusEnum.PENDING)

    # Financial metrics
    realized_pnl = Column(Float, default=0.0)
    unrealized_pnl = Column(Float, default=0.0)
    fees = Column(Float, default=0.0)

    # Risk metrics
    stop_loss = Column(Float)
    take_profit = Column(Float)
    position_size = Column(Float)

    # Timestamps
    entry_time = Column(DateTime, default=datetime.utcnow, index=True)
    exit_time = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Additional metadata
    metadata = Column(JSON, default={})

    # Relationships
    agent = relationship("TradingAgent", back_populates="trades")
    signal = relationship("TradingSignalRecord", back_populates="trade")


class BacktestResult(Base):
    """
    Backtest Results

    Stores backtesting results for agents
    """
    __tablename__ = "backtest_results"

    id = Column(Integer, primary_key=True, index=True)

    # Test identification
    test_name = Column(String, nullable=False)
    agent_type = Column(Enum(AgentTypeEnum), nullable=False)

    # Test parameters
    symbol = Column(String, nullable=False)
    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=False)
    initial_capital = Column(Float, default=100000.0)

    # Configuration used
    agent_config = Column(JSON, default={})

    # Performance metrics
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)

    # Financial metrics
    total_return = Column(Float, default=0.0)
    total_return_pct = Column(Float, default=0.0)
    annualized_return = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, default=0.0)
    sortino_ratio = Column(Float, default=0.0)
    max_drawdown = Column(Float, default=0.0)
    max_drawdown_pct = Column(Float, default=0.0)

    # Trade statistics
    avg_win = Column(Float, default=0.0)
    avg_loss = Column(Float, default=0.0)
    largest_win = Column(Float, default=0.0)
    largest_loss = Column(Float, default=0.0)
    avg_trade_duration = Column(Float, default=0.0)  # in hours

    # Risk metrics
    value_at_risk = Column(Float)
    expected_shortfall = Column(Float)

    # Detailed results
    equity_curve = Column(JSON, default=[])  # List of equity values over time
    trade_history = Column(JSON, default=[])  # List of all trades

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    # Additional metadata
    metadata = Column(JSON, default={})


class AgentPerformanceSnapshot(Base):
    """
    Agent Performance Snapshots

    Periodic snapshots of agent performance for tracking over time
    """
    __tablename__ = "agent_performance_snapshots"

    id = Column(Integer, primary_key=True, index=True)

    # Agent reference
    agent_id = Column(Integer, ForeignKey("trading_agents.id"), nullable=False)

    # Performance metrics at snapshot time
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    win_rate = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, default=0.0)
    max_drawdown = Column(Float, default=0.0)

    # Market conditions at snapshot
    market_volatility = Column(Float)
    market_trend = Column(String)  # "bullish", "bearish", "sideways"

    # Snapshot metadata
    snapshot_date = Column(DateTime, default=datetime.utcnow, index=True)
    period = Column(String)  # "daily", "weekly", "monthly"

    # Additional metrics
    metadata = Column(JSON, default={})
